name: Go Build and Test

on: pull_request

jobs:
  build-and-test:
    name: Build and Test the Go code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest
      - name: Run gofumpt
        run: gofumpt -l -w .
      - name: make verification
        run: make verifiers
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
